[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "brainlm"
version = "0.1.0"
description = "BrainLM"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "accelerate",
    "datasets",
    # "flash-attn",  # flash-attn not required
    "ipython",
    "jupyter",
    "matplotlib",
    "nibabel",
    "numba>=0.57.0",  # lower bound version to uv resolution issue
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "seaborn",
    "torch",
    "tqdm",
    "transformers<4.31",
    "umap-learn",
    "wandb",
]
